export const locations = [
  "🌏 Remote",
  "🦁 Africa",
  "⛩ Asia",
  "🇪🇺 Europe",
  "💃 Latin America",
  "🕌 Middle East",
  "⛰️ North America",
  "🌊 Oceania",
  "🇦🇫 Afghanistan",
  "🇦🇱 Albania",
  "🇩🇿 Algeria",
  "🇦🇸 American Samoa",
  "🇦🇩 Andorra",
  "🇦🇴 Angola",
  "🇦🇮 Anguilla",
  "🇦🇶 Antarctica",
  "🇦🇬 Antigua and Barbuda",
  "🇦🇷 Argentina",
  "🇦🇲 Armenia",
  "🇦🇼 Aruba",
  "🇦🇺 Australia",
  "🇦🇹 Austria",
  "🇦🇿 Azerbaijan",
  "🇧🇭 Bahrain",
  "🇧🇩 Bangladesh",
  "🇧🇧 Barbados",
  "🇧🇾 Belarus",
  "🇧🇪 Belgium",
  "🇧🇿 Belize",
  "🇧🇯 Benin",
  "🇧🇲 Bermuda",
  "🇧🇹 Bhutan",
  "🇧🇴 Bolivia",
  "🇧🇦 Bosnia",
  "🇧🇼 Botswana",
  "🇧🇻 Bouvet Island",
  "🇧🇷 Brazil",
  "🇮🇴 British Indian Ocean Territory",
  "🇻🇬 British Virgin Islands",
  "🇧🇳 Brunei",
  "🇧🇬 Bulgaria",
  "🇧🇫 Burkina Faso",
  "🇧🇮 Burundi",
  "🇰🇭 Cambodia",
  "🇨🇲 Cameroon",
  "🇨🇦 Canada",
  "🇨🇻 Cape Verde",
  "🇧🇶 Caribbean Netherlands",
  "🇰🇾 Cayman Islands",
  "🇨🇫 Central African Republic",
  "🇹🇩 Chad",
];

export const benefits = [
  "401(k)",
  "Distributed Team",
  "Async",
  "Vision Insurance",
  "Dental Insurance",
  "Medical Insurance",
  "Unlimited vacation",
  "Paid time off",
  "4 day workweek",
  "401k matching",
  "Company retreats",
  "Coworking budget",
  "Learning budget",
  "Free gym membership",
  "Mental wellness budget",
  "Home office budget",
  "Pay in crypto",
  "Pseudonymous",
  "Profit sharing",
  "Equity compensation",
  "No whiteboard interview",
  "No monitoring system",
  "No politics at work",
  "We hire old (young)",
];
